# Generated by Django 3.2.4 on 2021-08-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minister', '0001_initial'),
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('donation_type', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('notes', models.TextField()),
                ('monthly', models.BooleanField()),
                ('minister', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='minister.minister')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ministry.ministry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
