# Generated by Django 3.2.4 on 2021-09-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20210902_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('content', models.ManyToManyField(to='videos.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
