# Generated by Django 3.2.4 on 2021-09-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sms',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
