# Generated by Django 3.2.4 on 2021-10-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatty', '0002_chat_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_type',
            field=models.CharField(choices=[('N', 'Normal'), ('W', 'Whatsapp'), ('E', 'Email')], default='N', max_length=50),
        ),
    ]
