# Generated by Django 3.2.4 on 2021-09-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evangelism', '0002_auto_20210906_0526'),
        ('minister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minister',
            name='field_name',
        ),
        migrations.AddField(
            model_name='minister',
            name='fields',
            field=models.ManyToManyField(to='evangelism.Evangelism'),
        ),
    ]
