# Generated by Django 3.2.4 on 2021-08-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sort_by_date', models.BooleanField()),
                ('podcast_type', models.CharField(choices=[('E', 'Episode'), ('S', 'Series')], default='E', max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('published', models.DateField()),
                ('language', models.CharField(choices=[('K', 'Kiswahili'), ('E', 'English')], default='E', max_length=500)),
                ('region', models.CharField(max_length=255)),
                ('podcast', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
