# Generated by Django 3.2.4 on 2021-08-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('P', 'Published'), ('D', 'Draft')], default='D', max_length=50),
        ),
    ]
