# Generated by Django 3.2.4 on 2021-08-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210831_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Declined')], default='A', max_length=50),
        ),
        migrations.AddField(
            model_name='historicalcomments',
            name='status',
            field=models.CharField(choices=[('A', 'Approved'), ('D', 'Declined')], default='A', max_length=50),
        ),
    ]
