# Generated by Django 3.2.4 on 2021-08-31 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210831_0556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcomments',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='historicalcomments',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalBlog',
        ),
        migrations.DeleteModel(
            name='HistoricalComments',
        ),
    ]
