# Generated by Django 3.2.4 on 2021-09-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='home_church_phone_numbers',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
